server:
  port: 8090
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #修改心跳到5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间到15s
    ip-address: 127.0.0.1
    prefer-ip-address: true


mybatis:
  type-aliases-package: com.leyou.order.entity
  configuration:
    map-underscore-to-camel-case: true

ly:
  worker:
    workerId: 1 #当前数据中心中机器的编号
    dataCenterId: 1 #数据中心编号



  jwt:
    pubKeyPath: D:/heima/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN #cookie名称