server:
  port: 8082
spring:
  application:
    name: upload-service

      #上传文件大小 默认1m
#  servlet:
#    multipart:
#      max-file-size:

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间




logging:
  level:
    com.leyou: debug
