server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.133.130
    username: heima86
    password: heima86
    virtual-host: /heihei

ly:
  sms:
    accessKeyID:*********4 # 你自己的accessKeyId
    accessKeySecret: **************** # 你自己的AccessKeySecret
    signName: ******** # 签名名称
    verifyCodeTemplate: ********* # 模板名称
    domain: ************ # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id
