server:
  port: 8083
spring:
  application:
    name: search-service

  jackson:
    default-property-inclusion: non_null #包含到返回消息中的属性一定要有值，如果没有值，则取消返回
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.133.129:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间

logging:
  level:
    com.leyou: debug
    org.springframework: debug
