server:
  port: 8082
spring:
  application:
    name: upload-service

      #上传文件大小 默认1m
  servlet:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间


ly:
  oss:
    accessKeyId: LTAI4FmvincMrabnuMKPhcx4
    accessKeySecret: XnFpQvYY0waj2XBhE59NnMsKheBCQd
    host: http://fanleyou.oss-cn-shanghai.aliyuncs.com # 访问oss的域名，很重要bucket + endpoint
    endpoint: oss-cn-shanghai.aliyuncs.com # 你的服务的端点，不一定跟我一样
    dir: "" # 保存到bucket的某个子目录
    expireTime: 20 # 过期时间，单位是S
    maxFileSize: 5242880 #文件大小限制，这里是5M



logging:
  level:
    com.leyou: debug
