server:
  port: 8089

spring:
  application:
   name: cart-service

  jackson:
    default-property-inclusion: non_null #包含到返回消息中的属性一定要有值，如果没有值，则取消返回

  redis:
    host: 192.168.172.129


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间

logging:
  level:
    com.leyou: debug

ly:
  jwt:
    pubKeyPath: D:/heima/rsa/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN #cookie名称
