server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false

  rabbitmq:
    host: 192.168.133.130
    username: heima86
    password: heima86
    virtual-host: /heihei

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

    registry-fetch-interval-seconds: 5 #配置zuul作为服务的消费者的拉取周期，5s默认30

ly:
  static:
    itemDir: D:/heima/nginx-1.12.2/html/item
    itemTemplate: item